version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: ./infra/api/dev/Dockerfile.dev
    tty: true
    stdin_open: true
    volumes:
      - ./api:/var/www/html

  app:
    build: 
      context: .
      dockerfile: ./infra/app/dev/Dockerfile.dev
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    stdin_open: true
    volumes:
      - ./app:/home/node/admin

  web:
    build: 
      context: .
      dockerfile: ./infra/web/dev/Dockerfile.localhost.dev
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    volumes:
      - ./infra/db/init:/docker-entrypoint-initdb.d
  
  storage:
    build: 
      context: .
      dockerfile: ./infra/storage/Dockerfile
    ports:
      - 9020:9020
      - 9090:9090
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9090" /data --address :9020
    volumes:
      - ./infra/storage/.minio/data:/data
    
  mail:
    image: axllent/mailpit:v1.8
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025